
- hosts: 172.31.35.76
  become: yes
  tasks: 
  - include_tasks: file.yaml

  - name: I want to install webserver on ubuntu node
    apt:
      name: apache2
      state: present
    notify: restartwebserver
    
  - name: I want to copy myindex.j2 file
    template:
       src: myindex.j2
       dest: /var/www/html/index.html    
    notify: restartwebserver

  handlers:
  - name: restartwebserver
    service:
      name: apache2
      state: restarted
