---
- hosts: mywebservers
  become: yes
  tasks: 
- name: need to install Java on Redhat node only
  yum:
    name: "{{myjavepackonredhat}}"
    state: present
  when: ansible_os_family == "Redhat"

- name: need to install Java on ubuntu node only
  apt:
    name: "{{myjavapackonubuntu}}"
    state: present
  when: ansible_os_family == "Debian"

  