---
- hosts: mywebservers
  become: yes
  tasks: 
  - name: need to install Java on ubuntu node only
    apt:
     name: "{{myjavapackonubuntu}}"
     state: present
    when: ansible_os_family == "Debian"

  - name: need to install Java on RedHat node only
    yum:
     name: "{{myjavapackonRedHat}}"
     state: present
    when: ansible_os_family == "RedHat"

  

  