---
- hosts: mywebservers
  become: yes
  tasks: 
  -  name: need to install Java on ubuntu 
     apt:
      name: "{{myjavapackonubuntu}}"
      state: present
     When: ansible_os_family =="Debian"

  - name: need to install Java on Redhat 
    yum:
      name: "{{myjavepackonredhat}}"
      state: present
    When: ansible_os_family =="Redhat"