---
- hosts: all
  become: yes
  tasks:
  -  name: install webserver on debian node only
     apt: 
      name: apache2
      state: present
     when: ansible_os_family=="Debian"
  -  name: install webserver on Redhat node only
     yum:
       name: httpd
       state: present
     when: ansible_os_family=="RedHat"